language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"

notifications:
  on_success: change
  on_failure: change

# Miniconda-based setup of the Scipy stack based on
# https://gist.github.com/dan-blanchard/7045057.

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy pysam matplotlib seaborn pandas
  - python setup.py install

script: python plot_coverage.py yeast_test_small.bam

before_script:
  - pip install coveralls
#  - coverage run --source=census setup.py test

sudo: false

after_success:
  - coveralls
